In [141]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from matplotlib import rc

# 한글 폰트 설정 (맑은 고딕)
plt.rc('font', family='Malgun Gothic')

# 마이너스 기호 깨짐 방지
plt.rcParams['axes.unicode_minus'] = False

In [142]:
users = pd.read_csv("users.csv", encoding= 'utf-8')
products = pd.read_csv("products.csv", encoding= 'utf-8')
orders = pd.read_csv("orders.csv", encoding= 'utf-8')
order_items = pd.read_csv("order_items.csv", encoding= 'utf-8')
inventory_items = pd.read_csv("inventory_items.csv", encoding= 'utf-8')
distribution_centers = pd.read_csv("distribution_centers.csv", encoding= 'utf-8')
events = pd.read_csv("events.csv", encoding= 'utf-8')

C:\Users\chb82\AppData\Local\Temp\ipykernel_2512\354653330.py:1: DtypeWarning: Columns (8) have mixed types. Specify dtype option on import or set low_memory=False.
  users = pd.read_csv("users.csv", encoding= 'utf-8')

## 불필요한 칼럼 삭제

#### users

In [143]:
users = pd.read_csv('users.csv')

columns_to_drop = ['first_name', 'last_name', 'email', 'city', 'street_address', 'user_geom']

users = users.drop(columns=columns_to_drop)

users.head()

C:\Users\chb82\AppData\Local\Temp\ipykernel_2512\1842538409.py:1: DtypeWarning: Columns (8) have mixed types. Specify dtype option on import or set low_memory=False.
  users = pd.read_csv('users.csv')

,id,age,gender,state,postal_code,country,latitude,longitude,traffic_source,created_at
0,3690,53,M,Acre,69980-000,Brasil,-8.065346,-72.870949,Search,2019-09-27 05:21:00+00:00
1,7472,43,M,Acre,69980-000,Brasil,-8.065346,-72.870949,Search,2023-02-03 00:00:00+00:00
2,75113,30,F,Acre,69980-000,Brasil,-8.065346,-72.870949,Search,2019-10-03 17:39:00+00:00
3,95254,30,M,Acre,69980-000,Brasil,-8.065346,-72.870949,Search,2021-04-14 03:30:00+00:00
4,38783,55,M,Acre,69980-000,Brasil,-8.065346,-72.870949,Search,2021-07-01 12:18:00+00:00

#### products

In [144]:
products = pd.read_csv('products.csv')

columns_to_drop = ['sku']

products = products.drop(columns=columns_to_drop)

products.head()

,id,cost,category,name,brand,retail_price,department,distribution_center_id
0,13842,2.51875,Accessories,Low Profile Dyed Cotton Twill Cap - Navy W39S55D,MG,6.25,Women,1
1,13928,2.33835,Accessories,Low Profile Dyed Cotton Twill Cap - Putty W39S55D,MG,5.95,Women,1
2,14115,4.87956,Accessories,Enzyme Regular Solid Army Caps-Black W35S45D,MG,10.99,Women,1
3,14157,4.64877,Accessories,Enzyme Regular Solid Army Caps-Olive W35S45D (...,MG,10.99,Women,1
4,14273,6.50793,Accessories,Washed Canvas Ivy Cap - Black W11S64C,MG,15.99,Women,1

#### events

In [145]:
events = pd.read_csv('events.csv')

columns_to_drop = ['ip_address', 'city', 'state', 'postal_code']

events = events.drop(columns=columns_to_drop)

events.head()

,id,user_id,sequence_number,session_id,created_at,browser,traffic_source,uri,event_type
0,1641988,NaN,3,5bf6673a-4f32-48cd-9494-d4d145f56bb3,2025-08-30 18:34:00+00:00,Chrome,Adwords,/cancel,cancel
1,1382041,NaN,3,fbf23a93-69af-4084-8132-d6359538ca05,2022-11-29 14:00:00+00:00,Chrome,Adwords,/cancel,cancel
2,2284087,NaN,3,8539547d-c485-42f9-aa9e-dc1884f77b50,2019-04-14 11:21:00+00:00,Safari,Facebook,/cancel,cancel
3,1634021,NaN,3,85213078-5a7a-465f-b79f-9d5ffebf9014,2022-04-28 07:19:00+00:00,Chrome,Email,/cancel,cancel
4,1583972,NaN,3,d6752dc3-eb62-4ab7-a799-2aaf60b4ce3b,2025-02-24 18:26:00+00:00,Chrome,Adwords,/cancel,cancel

## 결측치 삭제 및 대체

#### products

In [146]:
products = products.dropna(subset=['name', 'brand']) # subset을 사용하면 다른 컬럼에 결측치가 있어도 유지.

#### orders

In [147]:
no_data = orders[orders['delivered_at'].notnull()]

status_counts = no_data['status'].value_counts()

print(status_counts)

status
Complete    31344
Returned    12581
Name: count, dtype: int64

In [148]:
# returned_at가 값이 있는 경우 :  Returned(12581) / 값이 없는 경우 : Shipped(37763), Complete(31344), Processing(25287), Cancelled(18492)
# shipped_at 값이 있는 경우 : Shipped(37763), Complete(31344), Returned(12581) / 값이 없는 경우 : Processing(25287), Cancelled(18492)
# delivered_at 값이 있는 경우 : Complete(31344), Returned(12581) / 값이 없는 경우 : Shipped(37763), Processing(25287), Cancelled(18492)

In [149]:
orders['returned_at'] = orders['returned_at'].fillna(0)
orders['shipped_at'] = orders['shipped_at'].fillna(0)
orders['delivered_at'] = orders['delivered_at'].fillna(0)

#### order_items

In [150]:
no_data = order_items[order_items['delivered_at'].notnull()]

status_counts = no_data['status'].value_counts()

print(status_counts)

status
Complete    45127
Returned    18128
Name: count, dtype: int64

In [151]:
# returned_at가 값이 있는 경우 :  Returned(18128) / 값이 없는 경우 : Shipped(54641), Complete(45127), Processing(36961), Cancelled(26891)
# shipped_at 값이 있는 경우 : Shipped(54641), Complete(45127), Returned(18128) / 값이 없는 경우 : Processing(36961), Cancelled(26891)
# delivered_at 값이 있는 경우 : Complete(45127), Returned(18128) / 값이 없는 경우 : Shipped(54641), Processing(36961), Cancelled(26891)

In [152]:
order_items['returned_at'] = order_items['returned_at'].fillna(0)
order_items['shipped_at'] = order_items['shipped_at'].fillna(0)
order_items['delivered_at'] = order_items['delivered_at'].fillna(0)

#### inventory_items

In [153]:
inventory_items['sold_at'] = inventory_items['sold_at'].fillna(0) # 매개변수 만들기?

In [154]:
inventory_items = inventory_items.dropna(subset=['product_name', 'product_brand'])

#### events

In [155]:
events['user_id'] = events['user_id'].fillna(0)

## 인덱스 리셋

In [156]:
users = users.reset_index(drop=True)

users.head()

,id,age,gender,state,postal_code,country,latitude,longitude,traffic_source,created_at
0,3690,53,M,Acre,69980-000,Brasil,-8.065346,-72.870949,Search,2019-09-27 05:21:00+00:00
1,7472,43,M,Acre,69980-000,Brasil,-8.065346,-72.870949,Search,2023-02-03 00:00:00+00:00
2,75113,30,F,Acre,69980-000,Brasil,-8.065346,-72.870949,Search,2019-10-03 17:39:00+00:00
3,95254,30,M,Acre,69980-000,Brasil,-8.065346,-72.870949,Search,2021-04-14 03:30:00+00:00
4,38783,55,M,Acre,69980-000,Brasil,-8.065346,-72.870949,Search,2021-07-01 12:18:00+00:00

In [157]:
products= products.reset_index(drop=True)

products.head()

,id,cost,category,name,brand,retail_price,department,distribution_center_id
0,13842,2.51875,Accessories,Low Profile Dyed Cotton Twill Cap - Navy W39S55D,MG,6.25,Women,1
1,13928,2.33835,Accessories,Low Profile Dyed Cotton Twill Cap - Putty W39S55D,MG,5.95,Women,1
2,14115,4.87956,Accessories,Enzyme Regular Solid Army Caps-Black W35S45D,MG,10.99,Women,1
3,14157,4.64877,Accessories,Enzyme Regular Solid Army Caps-Olive W35S45D (...,MG,10.99,Women,1
4,14273,6.50793,Accessories,Washed Canvas Ivy Cap - Black W11S64C,MG,15.99,Women,1

In [158]:
orders= orders.reset_index(drop=True)

orders.head()

,order_id,user_id,status,gender,created_at,returned_at,shipped_at,delivered_at,num_of_item
0,48,37,Cancelled,F,2024-08-22 01:33:47+00:00,0,0,0,1
1,76,65,Cancelled,F,2025-08-16 19:33:04+00:00,0,0,0,1
2,92,75,Cancelled,F,2021-09-25 05:34:45+00:00,0,0,0,2
3,119,97,Cancelled,F,2022-06-28 18:03:57+00:00,0,0,0,1
4,124,101,Cancelled,F,2024-06-30 15:21:22+00:00,0,0,0,1

In [159]:
order_items= order_items.reset_index(drop=True)

order_items.head()

,id,order_id,user_id,product_id,inventory_item_id,status,created_at,shipped_at,delivered_at,returned_at,sale_price
0,30624,21284,16892,14235,82570,Complete,2025-06-29 07:34:04+00:00,2025-06-29 13:06:36+00:00,2025-07-01 14:24:36+00:00,0,0.02
1,48427,33577,26659,14235,130515,Complete,2025-09-09 21:49:07+00:00,2025-09-07 19:50:43+00:00,2025-09-10 03:08:43+00:00,0,0.02
2,82129,56839,44907,14235,221524,Complete,2023-09-07 01:59:10+00:00,2023-09-06 06:10:35+00:00,2023-09-07 12:48:35+00:00,0,0.02
3,121090,83627,66403,14235,326621,Processing,2025-01-15 17:51:27+00:00,0,0,0,0.02
4,127935,88339,70173,14235,345011,Processing,2022-02-08 09:23:26+00:00,0,0,0,0.02

In [160]:
inventory_items= inventory_items.reset_index(drop=True)

inventory_items.head()

,id,product_id,created_at,sold_at,cost,product_category,product_name,product_brand,product_retail_price,product_department,product_sku,product_distribution_center_id
0,18988,13844,2024-07-18 08:26:30+00:00,2024-09-13 21:58:30+00:00,2.76804,Accessories,(ONE) 1 Satin Headband,Funny Girl Designs,6.99,Women,2A3E953A5E3D81E67945BCE5519F84C8,7
1,18989,13844,2022-09-30 14:02:00+00:00,0,2.76804,Accessories,(ONE) 1 Satin Headband,Funny Girl Designs,6.99,Women,2A3E953A5E3D81E67945BCE5519F84C8,7
2,98138,13844,2025-08-04 07:18:50+00:00,2025-09-29 01:29:50+00:00,2.76804,Accessories,(ONE) 1 Satin Headband,Funny Girl Designs,6.99,Women,2A3E953A5E3D81E67945BCE5519F84C8,7
3,98139,13844,2020-02-23 04:34:00+00:00,0,2.76804,Accessories,(ONE) 1 Satin Headband,Funny Girl Designs,6.99,Women,2A3E953A5E3D81E67945BCE5519F84C8,7
4,234601,13844,2022-08-03 15:42:36+00:00,2022-08-15 15:20:36+00:00,2.76804,Accessories,(ONE) 1 Satin Headband,Funny Girl Designs,6.99,Women,2A3E953A5E3D81E67945BCE5519F84C8,7

In [161]:
events = events.reset_index(drop=True)

events.head()

,id,user_id,sequence_number,session_id,created_at,browser,traffic_source,uri,event_type
0,1641988,0.0,3,5bf6673a-4f32-48cd-9494-d4d145f56bb3,2025-08-30 18:34:00+00:00,Chrome,Adwords,/cancel,cancel
1,1382041,0.0,3,fbf23a93-69af-4084-8132-d6359538ca05,2022-11-29 14:00:00+00:00,Chrome,Adwords,/cancel,cancel
2,2284087,0.0,3,8539547d-c485-42f9-aa9e-dc1884f77b50,2019-04-14 11:21:00+00:00,Safari,Facebook,/cancel,cancel
3,1634021,0.0,3,85213078-5a7a-465f-b79f-9d5ffebf9014,2022-04-28 07:19:00+00:00,Chrome,Email,/cancel,cancel
4,1583972,0.0,3,d6752dc3-eb62-4ab7-a799-2aaf60b4ce3b,2025-02-24 18:26:00+00:00,Chrome,Adwords,/cancel,cancel

## 결측치 확인

In [162]:
users.isnull().sum()

id                0
age               0
gender            0
state             0
postal_code       0
country           0
latitude          0
longitude         0
traffic_source    0
created_at        0
dtype: int64

In [163]:
products.isnull().sum()

id                        0
cost                      0
category                  0
name                      0
brand                     0
retail_price              0
department                0
distribution_center_id    0
dtype: int64

In [164]:
orders.isnull().sum()

order_id        0
user_id         0
status          0
gender          0
created_at      0
returned_at     0
shipped_at      0
delivered_at    0
num_of_item     0
dtype: int64

In [165]:
order_items.isnull().sum()

id                   0
order_id             0
user_id              0
product_id           0
inventory_item_id    0
status               0
created_at           0
shipped_at           0
delivered_at         0
returned_at          0
sale_price           0
dtype: int64

In [166]:
inventory_items.isnull().sum()

id                                0
product_id                        0
created_at                        0
sold_at                           0
cost                              0
product_category                  0
product_name                      0
product_brand                     0
product_retail_price              0
product_department                0
product_sku                       0
product_distribution_center_id    0
dtype: int64

In [167]:
distribution_centers.isnull().sum()

id                          0
name                        0
latitude                    0
longitude                   0
distribution_center_geom    0
dtype: int64

In [168]:
events.isnull().sum()

id                 0
user_id            0
sequence_number    0
session_id         0
created_at         0
browser            0
traffic_source     0
uri                0
event_type         0
dtype: int64

## 추가 칼럼 수정

#### 1. España -> Spain

In [169]:
users['country'].value_counts()

country
China             33996
United States     22448
Brasil            14334
South Korea        5371
France             4726
United Kingdom     4664
Germany            4177
Spain              4028
Japan              2493
Australia          2198
Belgium            1318
Poland              228
Colombia             14
España                3
Austria               2
Name: count, dtype: int64

In [170]:
# 1. 'Espana'를 'Spain'으로 변경합니다.
# dict 형태 {'기존값': '바꿀값'}를 사용하여 정확하게 매칭합니다.
users['country'] = users['country'].replace({'España': 'Spain'})

# 2. 결과 확인 (제대로 바뀌었는지 unique 값 확인)
print(users['country'].unique())

['Brasil' 'Japan' 'United States' 'Colombia' 'Spain' 'China' 'Australia'
 'France' 'Germany' 'Belgium' 'South Korea' 'Poland' 'United Kingdom'
 'Austria']

#### 2. id 칼럼 이름 변경

In [171]:
# users
# id (고객 고유 ID) - user_id로 변경

# products
# id (상품 고유 ID) - product_id로 변경

# orders
# order_id (주문 고유 ID)
# user_id (주문한 고객 ID)

# order_items
# id (아이템별 고유 ID) - order_items_id로 변경
# order_id (주문 ID)
# user_id (유저 ID)
# product_id (상품 ID)
# inventory_item_id (연결된 재고 ID)

# inventory_items
# id (재고 고유 ID) - inventory_items_id로 변경
# product_id (상품 ID)

# distribution_centers
# id (센터 ID) - centers_id로 변경

# events
# id (이벤트 고유 ID) - event_id로 변경
# user_id (유저 ID)
# session_id (세션 ID)

In [172]:
users = users.rename(columns={'id': 'user_id'})

print("변경된 칼럼 목록:", users.columns.tolist())

변경된 칼럼 목록: ['user_id', 'age', 'gender', 'state', 'postal_code', 'country', 'latitude', 'longitude', 'traffic_source', 'created_at']

In [173]:
products = products.rename(columns={'id': 'product_id'})

print("변경된 칼럼 목록:", products.columns.tolist())

변경된 칼럼 목록: ['product_id', 'cost', 'category', 'name', 'brand', 'retail_price', 'department', 'distribution_center_id']

In [174]:
order_items = order_items.rename(columns={'id': 'order_item_id'})

print("변경된 칼럼 목록:", order_items.columns.tolist())

변경된 칼럼 목록: ['order_item_id', 'order_id', 'user_id', 'product_id', 'inventory_item_id', 'status', 'created_at', 'shipped_at', 'delivered_at', 'returned_at', 'sale_price']

In [175]:
inventory_items = inventory_items.rename(columns={'id': 'inventory_item_id'})

print("변경된 칼럼 목록:", inventory_items.columns.tolist())

변경된 칼럼 목록: ['inventory_item_id', 'product_id', 'created_at', 'sold_at', 'cost', 'product_category', 'product_name', 'product_brand', 'product_retail_price', 'product_department', 'product_sku', 'product_distribution_center_id']

In [176]:
distribution_centers = distribution_centers.rename(columns={'id': 'center_id'})

print("변경된 칼럼 목록:", distribution_centers.columns.tolist())

변경된 칼럼 목록: ['center_id', 'name', 'latitude', 'longitude', 'distribution_center_geom']

In [177]:
events = events.rename(columns={'id': 'event_id'})

print("변경된 칼럼 목록:", events.columns.tolist())

변경된 칼럼 목록: ['event_id', 'user_id', 'sequence_number', 'session_id', 'created_at', 'browser', 'traffic_source', 'uri', 'event_type']

#### 3. created_at 수정

#### 4. 브랜드 특수문자 삭제

## 조인?